apiVersion: apps/v1
kind: Deployment
metadata:
 name: test4
 labels:
    app: test4
spec:
 replicas: 2
 selector:
    matchLabels:
      app: test4
 template:
    metadata:
       labels:
        app: test4
    spec:
      containers:
      - name: test4container
        image: docker.io/jptabja/test3:latest
        ports:
        - containerPort: 8080